namespace ctr_wp7.ctr_original
{
    public enum UNLOCKED_STATE
    {
        UNLOCKED_STATE_LOCKED,
        UNLOCKED_STATE_UNLOCKED,
        UNLOCKED_STATE_JUST_UNLOCKED,
        UNLOCKED_STATE_JUST_UNLOCKED_WITH_CHEAT,
        UNLOCKED_STATE_LOCKED_SHAREWARE
    }
}
